name: GitHub Pages

on:
  push:
    branches:
      - develop # Set a branch name to trigger deployment
  # pull_request:
  #   types: [closed]

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: npm install
        run: npm install
      - name: gatsby build
        run: yarn build
      - name: gh-pages
        run: gh-pages -u \"narapickle <narapickle@gmail.com>\" -d public -b master
